config/routes.rb
Ratebeer::Application.routes.draw do

  resources :styles, except: [:new, :create]
  resources :memberships, except: [:edit, :update] do
    member do
      post 'confirm'
    end
  end
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries do
    member do
      post 'toggle_activity'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources 'ratings', only: [:index, :new, :create, :destroy]

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#callback'
  post 'auth/:provider/callback', to: 'sessions#callback'
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy'

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'brewerylist', to:'breweries#list'

  root 'breweries#index'

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  validates :user, uniqueness: { scope: :beer_club, message: "can't join same club twice" }
  after_initialize :init

  belongs_to :user
  belongs_to :beer_club

  scope :confirmed, -> { where confirmed: true }
  scope :unconfirmed, -> { where confirmed: false | nil }

  private

    def init
      self.confirmed ||= false
    end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :destroy, :confirm]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @beer_clubs = BeerClub.all
    @membership = Membership.new
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)
    @membership.user = current_user

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership.beer_club, notice: "#{@membership.user.username}, welcome to the club!" }
        format.json { render action: 'show', status: :created, location: @membership }
      else
        @beer_clubs = BeerClub.all.reject { |b| b.members.include? current_user }
        format.html { render action: 'new' }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url }
      format.json { head :no_content }
    end
  end

  def confirm
    @membership.update_attribute :confirmed, true

    redirect_to :back, notice:"Member #{@membership.user} has been approved"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:beer_club_id, :user_id)
    end
end

app/views/memberships/_form.html.slim
= form_for membership do |f|
  - if membership.errors.any?
    #error_explanation
      h2 = "#{pluralize(membership.errors.count, "error")} prohibited this membership from being saved:"
      ul
        - membership.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :beer_club_id
    = f.select :beer_club_id, options_from_collection_for_select(beer_clubs, :id, :name)
  .field
    = f.hidden_field :user_id, value: current_user.id
  .action
   = f.submit 'Save', class: 'ui tiny positive button'

app/views/memberships/index.html.slim
h1 Listing memberships

table.ui.table.segment
  thead
    tr
      th Beer club
      th User
      th
      th

  - @memberships.each do |membership|
    tr
      td = membership.beer_club_id
      td = membership.user_id
      td = link_to 'Show', membership
      td = link_to 'Edit', edit_membership_path(membership), class: 'ui mini button circular'
      td = link_to 'Destroy', membership, data: {confirm: 'Are you sure?'}, method: :delete, class: 'ui mini negative button circular'

br

= link_to 'New Membership', new_membership_path

app/views/memberships/new.html.slim
h1 New membership

== render 'form', membership: @membership, beer_clubs: @beer_clubs

= link_to 'Back', memberships_path

app/views/memberships/show.html.slim
p
  strong Beer club:
  = link_to @membership.beer_club.name, @membership.beer_club
p
  strong User:
  = link_to @membership.user.username, @membership.user

= link_to 'Edit', edit_membership_path(@membership)
'|
= link_to 'Back', memberships_path