config/routes.rb
Ratebeer::Application.routes.draw do

  resources :styles, except: [:new, :create]
  resources :memberships, except: [:edit, :update] do
    member do
      post 'confirm'
    end
  end
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries do
    member do
      post 'toggle_activity'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources 'ratings', only: [:index, :new, :create, :destroy]

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#callback'
  post 'auth/:provider/callback', to: 'sessions#callback'
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy'

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'brewerylist', to:'breweries#list'

  root 'breweries#index'

end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  has_many :memberships
  has_many :members, through: :memberships, source: :user
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @membership = Membership.new
    @membership.beer_club = @beer_club
    @unconfirmed_members = Membership.where(confirmed: false)
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)
    @beer_club.memberships << Membership.new( user: current_user)
    shared_create(@beer_club)
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    shared_update(@beer_club, beer_club_params)
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city)
    end
end

app/views/beer_clubs/_form.html.slim
= form_for beer_club do |f|
  - if beer_club.errors.any?
    #error_explanation
      h2 = "#{pluralize(beer_club.errors.count, "error")} prohibited this beer_club from being saved:"
      ul
        - beer_club.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :founded
    = f.number_field :founded
  .field
    = f.label :city
    = f.text_field :city
  .action
    = f.submit 'Save', class: 'ui tiny positive button'

app/views/beer_clubs/edit.html.slim
h1 Editing beer_club

== render 'form', beer_club: @beer_club

= link_to 'Show', @beer_club
'|
= link_to 'Back', beer_clubs_path

app/views/beer_clubs/index.html.slim
h1 Listing Beer clubs

table.ui.table.segment
  thead
    tr
      th Name
      th Founded
      th City
      th
      th

  - @beer_clubs.each do |beer_club|
    tr
      td = link_to beer_club.name, beer_club
      td = beer_club.founded
      td = beer_club.city
      td = link_to 'Edit', edit_beer_club_path(beer_club), class: 'ui mini button circular' if current_user
      td = link_to 'Destroy', beer_club, data: {confirm: 'Are you sure?'}, method: :delete, class: 'ui mini negative button circular' if current_user

br

= link_to 'New Beer club', new_beer_club_path

app/views/beer_clubs/new.html.slim
h1 New beer_club

== render 'form', beer_club: @beer_club

= link_to 'Back', beer_clubs_path

app/views/beer_clubs/show.html.slim
p
  strong Name:
  = @beer_club.name
p
  strong Founded:
  = @beer_club.founded
p
  strong City:
  = @beer_club.city

p
  strong Has #{pluralize(@beer_club.members.count, 'member')}:
ul
  - @beer_club.members.each do |u|
    li = link_to u, u

- if current_user
  - unless @beer_club.members.include? current_user
    = form_for @membership do |f|
      = f.hidden_field :beer_club_id
      .action
        = f.submit 'Join the club', class: 'ui tiny positive button'
  - if @unconfirmed_members.present?
    h3 Outstanding applications
    ul
      - @unconfirmed_members.each do |m|
        li
        = link_to m.user
        '
        = link_to 'Confirm', confirm_membership_path(m), class: 'ui button circular blue'

= edit_and_destroy_buttons(@beer_club)
= link_to 'Back', beer_clubs_path, class: 'ui mini button circular'