config/routes.rb
Ratebeer::Application.routes.draw do

  resources :styles, except: [:new, :create]
  resources :memberships, except: [:edit, :update] do
    member do
      post 'confirm'
    end
  end
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries do
    member do
      post 'toggle_activity'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources 'ratings', only: [:index, :new, :create, :destroy]

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#callback'
  post 'auth/:provider/callback', to: 'sessions#callback'
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy'

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'brewerylist', to:'breweries#list'

  root 'breweries#index'

end

app/models/brewery.rb
require 'date'

class Brewery < ActiveRecord::Base
  include RatingAverage, CollectionCache

  validates :name, presence: :true
  validates :year, numericality: { only_integer: true, less_than_or_equal_to: ->(x) { Date.today.year }, greater_than_or_equal_to: 1042 }

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  scope :active, -> { where active: true }
  scope :retired, -> { where active: [nil,false] }

  def to_s
    name
  end

  def self.top(n)
   Brewery.all.sort_by{ |b| -(b.average_rating||0) }.take(n)
   # palauta listalta parhaat n kappaletta
   # miten? ks. http://www.ruby-doc.org/core-2.1.0/Array.html
 end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy, :toggle_activity]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :skip_if_cached, only:[:index]

  # GET /breweries
  # GET /breweries.json
  def index

    @active_breweries = Brewery.active.order(@order)
    @retired_breweries = Brewery.retired.order(@order)
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)
    shared_create(@brewery, breweries_path)
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    shared_update(@brewery, brewery_params)
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url }
      format.json { head :no_content }
    end
  end

  def list
  end

  def toggle_activity
    @brewery.update_attribute :active, (not @brewery.active)

    new_status = @brewery.active? ? "active" : "retired"

    redirect_to :back, notice:"brewery activity status changed to #{new_status}"
  end

  private
    def skip_if_cached
      @order = params[:order] || 'name'
      return render :index if fragment_exist?([Brewery.cache_key_collection, @order])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year, :active)
    end
end

app/views/breweries/_brewery.html.slim
tr
  td = link_to brewery.name, brewery
  td = brewery.year

app/views/breweries/_form.html.slim
= form_for brewery do |f|
  - if brewery.errors.any?
    #error_explanation
      h2 = "#{pluralize(brewery.errors.count, "error")} prohibited this brewery from being saved:"
      ul
        - brewery.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :year
    = f.text_field :year
  .field
    = f.label :active
    = f.check_box :active
  .action
    = f.submit 'Save', class: 'ui tiny positive button'

app/views/breweries/_list.html.slim
table.ui.table.segment
  thead
    tr
      th = link_to 'Name', breweries_path(order:"name")
      th = link_to 'Year', breweries_path(order:"year")
  = render breweries

app/views/breweries/edit.html.slim
h1 Editing brewery

== render 'form', brewery: @brewery

= link_to 'Show', @brewery
'|
= link_to 'Back', breweries_path

app/views/breweries/index.html.slim
h1 Breweries

- cache [Brewery.cache_key_collection, @order]
  h2 Active

  p Number of active breweries: #{@active_breweries.count}

  = render 'list', breweries: @active_breweries

  h2 Retired

  p Number of retired breweries: #{@retired_breweries.count}

  = render 'list', breweries: @retired_breweries
br

- if current_user
  = link_to 'New Brewery', new_brewery_path
  ' |
= link_to 'List of beers', beers_path

app/views/breweries/list.html.slim
script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.10/angular.min.js"
javascript:
  function BreweriesController($scope, $http) {
    $http.get('breweries.json').success( function(data, status, headers, config) {
      $scope.breweries = data;
    });

    $scope.order = 'name';

    $scope.click = function (order){
        $scope.order = order;
    }
    $scope.searchText = '';
  }

h2 Breweries

div [ng-app ng-controller="BreweriesController"]
  'search:
  input ng-model="searchText"
  table
    thead
      tr
        th
          a ng-click="click('name')" Name
        th
          a ng-click="click('year')" Year
        th
          a ng-click="click('beers.count')" Beers count
    tr ng-repeat="brewery in breweries | orderBy:order | filter:searchText"
      td
        '{{brewery.name}}
      td
        '{{brewery.year}}
      td
        '{{brewery.beers.count}}

app/views/breweries/new.html.slim
h1 New brewery

== render 'form', brewery: @brewery

= link_to 'Back', breweries_path

app/views/breweries/show.html.slim
- cache @brewery
  h2
    = @brewery.name
  - unless @brewery.active
    span.ui.label retired
  p
    em Established year: #{@brewery.year}

  p = link_to "change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "ui mini button"

  p Number of beers #{@brewery.beers.count}

  p
    - @brewery.beers.each do |beer|
      = link_to beer.name, beer
      '&nbsp;

  = render 'shared/ratings', object: @brewery

= edit_and_destroy_buttons(@brewery)
= link_to 'Back', breweries_path, class: 'mini ui circular button'