config/routes.rb
Ratebeer::Application.routes.draw do

  resources :styles, except: [:new, :create]
  resources :memberships, except: [:edit, :update] do
    member do
      post 'confirm'
    end
  end
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries do
    member do
      post 'toggle_activity'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources 'ratings', only: [:index, :new, :create, :destroy]

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#callback'
  post 'auth/:provider/callback', to: 'sessions#callback'
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy'

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'brewerylist', to:'breweries#list'

  root 'breweries#index'

end

app/views/layouts/_messages.html.slim
p#notice = notice

app/views/layouts/_navigation.html.slim
nav.ui.menu.inverted
  h3.header.item Ratebeer
  = link_to 'Breweries', breweries_path, class: 'item'
  = link_to 'Beers', beers_path, class: 'item'
  = link_to 'Styles', styles_path, class: 'item'
  = link_to 'Ratings', ratings_path, class: 'item'
  = link_to 'Users', users_path, class: 'item'
  = link_to 'Beer Clubs', beer_clubs_path, class: 'item'
  = link_to 'Places', places_path, class: 'item'
  .right.menu
    - unless current_user.nil?
      .ui.dropdown.item.simple
        i.icon.user
        = current_user.username
        i.icon.dropdown
        .menu
          = link_to 'My page', current_user, class: 'item'
          = link_to 'Rate a beer', new_rating_path, class: 'item'
          = link_to 'Join a club', new_membership_path, class: 'item'
          = link_to 'Signout', signout_path, method: :delete, class: 'item'
    - else
      .item
        = link_to 'Sign in', signin_path, class: 'ui button positive'
      .item
        = link_to 'Steam sign in', 'auth/steam', class: 'ui button positive'
      .item
        = link_to 'Signup', signup_path, class: 'ui blue button'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Ratebeer
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  body
    header
      = render 'layouts/navigation'

    main.container
      = render 'layouts/messages'
      .ui.grid
        .eight.wide.column
          == yield
        .four.wide.column
          img src="http://www.cs.helsinki.fi/u/mluukkai/wadror/pint.jpg" width="200"